version: "3"
services:
  db:
    image: 'bitnami/mongodb:latest'
    ports:
      - '27017:27017'
    networks:
      - net
    environment:
      MONGODB_USERNAME: demo
      MONGODB_PASSWORD: demo1234
      MONGODB_DATABASE: questioners
    volumes:
      - './containers/mongo:/data/db'
networks:
  net: